# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saitamau-maximum'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Format Test
        run: pnpm format:check

      - name: Lint Test
        run: pnpm lint

      - name: Build Test
        run: pnpm build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saitamau-maximum'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm build

      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks
        working-directory: packages/components
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
